### ISSUE TITLE
outline...

### ISSUE THREAD

**Issue by fiaful** [Aerthas/BLENDER-Arc-System-Works-Shader#1]
Hi, your shader looks excellent (at least from the images shown and from the video on youtube ... I hope to be able to test everything soon on my model in blender!)

I confess that I don't know much about shaders, and I probably didn't even understand the question exactly ... but could it have something to do with this post below?

[https://blender.stackexchange.com/questions/69971/how-do-you-add-a-thin-outline](https://blender.stackexchange.com/questions/69971/how-do-you-add-a-thin-outline)

I hope you find a way to realize what you are missing, that would be great!

**Comment by Aerthas** [comment]
Unfortunately this does not have much information that is useful. The proper things I need for the outline would be vertex offsetting geometry shader which currently does not exist in blender. However they are releasing a beta system of it in the upcoming blender 2.92, so I'm looking forward to that.
Right now outlines are done by just using the solidify modifier with the normals inverted.

**Comment by fiaful** [comment]
This sounds great! (especially considering that blender 2.92 will be released next week - 2021.02.24)

can't wait to see your next update as well (and also hope you will make an updated video on youtube!;))

good job and good luck!
